name: Generate Snake Animation

on:
  # 每天 UTC 时间 00:00 运行
  schedule:
    - cron: "0 0 * * *"
  
  # 允许手动触发
  workflow_dispatch:
  
  # 每次推送到 main 分支时运行
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # 生成贪吃蛇动画
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: lmqvq
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # 将生成的文件推送到仓库
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

